import './globals.css'
import { getServerSession } from 'next-auth/next'
import { authOptions } from '@/pages/api/auth/[...nextauth]'

import Nav from './components/Nav'
import Hydrate from './components/Hydrate'

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	const session = await getServerSession(authOptions)

	return (
		<html lang='en'>
			<body className='px-48'>
				<Hydrate>
					<Nav user={session?.user} />
					{children}
				</Hydrate>
			</body>
		</html>
	)
}
